# Generated by Django 4.0.4 on 2022-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_address_line_person_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
